# Generated by Django 3.0.7 on 2020-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200613_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
